services:

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./day20/.env

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
